config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  # root "articles#index"

  root to: 'home#index'

  get '/accounts', to: 'accounts#show'
  post '/accounts/login', to: 'accounts#login'
  post '/accounts/signup', to: 'accounts#signup'
  delete '/accounts/logout', to: 'accounts#logout'

  patch '/accounts/recover', to: 'accounts#trigger_recover_password'
  get '/accounts/recover', to: 'accounts#validate_recovery_token'
  patch '/accounts/reset/password', to: 'accounts#reset_password'

  resources :categories, only: %i[index]
  resources :products, only: %i[show index]

  resources :carts, except: %i[new delete] do
  end

  delete '/carts/remove/:id', to: 'carts#remove', as: 'remove_from_cart'

  resources :carts do
    collection do
      get '/guest/:token', to: 'carts#guest_order', as: 'guest_order'
      get '/my/review', to: 'carts#show'
    end
  end

  resources :checkouts do
    collection do
      post '/guest/buy', to: 'checkouts#guest_buy'
      post '/guest', to: 'checkouts#guest_create'

      post '/direct_buy', to: 'checkouts#direct_buy'
      post '/me/buy', to: 'checkouts#create', as: 'place_my_order'
    end
  end

  get '/me/addresses', to: 'addresses#index', as: 'addresses'
  get '/me/addresses/:id', to: 'address#edit', as: 'edit_address'

  # this is an idempotent route, if its update the params[:id] is present?
  # else its a new address for the current_user
  patch '/me/addresses', to: 'addresses#update', as: 'add_address'
  delete '/me/addresses/:id', to: 'addresses#delete', as: 'delete_address'

  match '*unmatched', to: 'application#not_found_method', via: :all
end

app/models/cart.rb
class Cart < ApplicationRecord
  self.primary_key = :cart_id

  validates :cart_id, :product_item_id, presence: true
  validates :cart_token, :cart_token_expires_at, presence: true
  validates :quantity, numericality: { in: 1..5 }

  STATE_PROCESSING = 'processing'.freeze
  STATE_ORDERED = 'ordered'.freeze

  scope :processing, -> { where(cart_state: STATE_PROCESSING) }

  # has_many :product_items,
  #          foreign_key: 'id',
  #          class_name: 'ProductItem',
  #          primary_key: 'product_item_id'
  #
  # since the cart is denormalized, meaning same cart_token is used for multiple items in cart
  # each cart entry will be related to only one product item
  has_one :product_item,
          foreign_key: 'id',
          class_name: 'ProductItem',
          primary_key: 'product_item_id'

  class << self
    def build_token
      SecureRandom.urlsafe_base64(32, false)
    end

    def build_id
      ULID.generate
    end

    def build_with_items(item_id:, item_props: ItemProperties.new)
      Cart.new(
        cart_token_expires_at: 4.days.since.utc,
        cart_state: STATE_PROCESSING,
        shareable: false,
        product_item_id: item_id,
        item_properties: item_props.encode,
        quantity: item_props.quantity
      )
    end

    def product_items_for_user(user_id, cart_token)
      Cart.joins(product_item: :product).where(
        cart_token:,
        cart_state: STATE_PROCESSING,
        user_id:
      ).where('carts.product_item_id = product_items.id')
    end

    def mark_as_ordered(cart_token, cart_id)
      Cart.where(cart_token:).or(Cart.where(cart_id:)).update_all(cart_state: STATE_ORDERED)
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include ApplicationHelper

  before_action :logged_in?
  before_action :set_cart_error_and_success_vars
  before_action :add_parent_crumb, only: %i[guest_order show]

  after_action :add_end_crumb, only: %i[guest_order show]

  # For registered users
  # get user_id from session[:user].id
  # get cart_token if cart_state: "processing"
  # For unregistered users return :unauthorized

  def edit; end

  def guest_order
    @product_item = ProductItem.includes(:product).find_by!(id: guest_cart_items[:item_id])
    @product = @product_item.product
    @form = GuestOrderBuilderForm.new
    @form.order_item_builder = guest_cart_items.slice(:item_id, :size, :quantity)
    @form.address_form_builder = {}

    @shipping = 0
    @discount = 0
    @outofstock = @product_item.quantity <= 0
    @total_amount = @product.price.to_i * guest_cart_items[:quantity].to_i

    @show_payment = false

    add_breadcrumb(@product.title, product_url(@product))
  end

  def show
    # calling cart_items here sets the @cart_items to be in view
    unless cart_items.present?
      flash[:notice] = 'You cart is empty'
      session.delete(:cart_token)

      return redirect_to products_url
    end

    @addresses = Address.viewable(current_user.id)
    @pricing = Pricing.new(items_in_cart: cart_items)
    @form = AddressFormBuilder.new
    @show_payment = false
    @order_form = MyOrderBuilderForm.new
  end

  def update
    item_props = ItemProperties.new(place_order_params.slice(:size, :color, :quantity))
    item_id = place_order_params[:item_id]
    @cart_items_count = 0

    @cart = Cart.build_with_items(item_props:, item_id:)

    if item_in_cart?(item_id)
      p 'current item is already updated'

      @cart_error_msgs << ['Only allowed to buy one']

      return respond_to do |format|
        format.html do
          flash[:error] = 'Something went wrong when adding to cart'
          redirect_back fallback_location: product_url(item_id), status: 422
        end

        format.turbo_stream do
          render turbo_stream: turbo_stream.replace(
            'cart-errors',
            partial: 'products/cart_messages',
            locals: { errors: @cart_error_msgs, success: [] }
          )
        end
      end
    end

    if current_cart.present?
      p 'cart is already present adding item'
      existing_cart = current_cart.first

      @cart.cart_id = existing_cart.cart_id
      # @cart.cart_id = Cart.build_id
      @cart.cart_token = existing_cart.cart_token
      @cart.cart_token_expires_at = existing_cart.cart_token_expires_at

      @cart_items_count = current_cart.count(1)
    else
      p 'building new cart'
      @cart.cart_id = Cart.build_id
      @cart.cart_token = Cart.build_token
    end

    @cart.user_id = current_user.id

    if @cart.valid? && @cart.save
      p 'saving to cart'

      session[:cart_token] = @cart.cart_token
      @cart_success_msgs << 'Added to cart'

      return respond_to do |format|
        format.turbo_stream

        format.html do
          flash.now[:success] = 'Item added to cart'
          redirect_back fallback_location: product_url(item_id), status: 201
        end
      end
    end

    p 'error while finding cart or building'
    @cart_error_msgs = @cart.errors.full_messages

    respond_to do |format|
      format.html do
        flash[:error] = 'Something went wrong when adding to cart'
        redirect_back fallback_location: product_url(item_id), status: 422
      end

      format.turbo_stream do
        render turbo_stream: turbo_stream.replace(
          'cart-errors',
          partial: 'products/cart_messages',
          locals: { errors: @cart_error_msgs, success: [] }
        )
      end
    end
  end

  def remove
    item_id = params[:id]
    nil unless item_in_cart?(item_id)

    @cart_items_count = current_cart.count
    cart_item = current_cart.find { |cart| cart.product_item_id == item_id }

    Cart.where(cart_id: cart_item.id, product_item_id: item_id).delete_all

    p @cart_items_count
    if @cart_items_count < 2
      flash[:success] = 'All items removed from cart'
      return redirect_to products_url
    end

    @item_id = item_id

    flash[:success] = 'Item removed from cart'
    redirect_to my_review_carts_url
  end

  private

  def item_in_cart?(item_id)
    current_cart.present? && current_cart.find { |cart| cart.product_item_id == item_id }.present?
  end

  def validate_token
    raise ::Unauthorized unless current_cart&.first&.cart_token == params[:token]
  end

  def guest_cart_items
    cart_token = session[:cart_token]

    raise ActiveRecord::RecordNotFound unless cart_token.present?
    raise ::Unauthorized unless cart_token == cart_token_in_params
    raise ActiveRecord::RecordNotFound unless session[cart_token].present?

    @guest_cart_items ||= HashWithIndifferentAccess.new session[cart_token]
  end

  def cart_items
    raise ::Unauthorized unless session[:cart_token].present?

    @cart_items ||= Cart.product_items_for_user(current_user.id, session[:cart_token])
  end

  def place_order_params
    params.require(:guest_buy_form).permit(:item_id, :size, :color, :quantity)
  end

  def cart_token_in_params
    params.fetch(:token, '')
  end

  def add_parent_crumb
    add_breadcrumb('Products', products_url)
  end

  def add_end_crumb
    add_breadcrumb('Checkout', nil, true)
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<div id="<%= dom_id cart %>">
</div>

app/views/carts/_cart_item.html.erb
<div class="cart-item" id='<%= dom_id(product_item) %>'>
  <div class="cart-image-wrapper">
    <%= image_tag product_item.product.promoted_image %>
  </div>
  <span class="inline-block cart-item-prod-title font-xs"><%= product.title %></span>
  <span class="inline-block"><%= format_price product.price %></span>
  <%= button_to "x", remove_from_cart_url(product_item.id), method: :delete, class: 'btn-cart-item-delete' %>
</div>

app/views/carts/_form.html.erb
<div class="checkout">
  <%= turbo_frame_tag 'guest-checkout-form' do %>
    <%= simple_form_for form, url: checkouts_url, method: :post, defaults: { wrapper_html: { class: 'guest_info_form_wrapper'}} do |f| %>
      <section id="user_info" class="guest_checkout_info_section">
        <h3>Contact Info</h3>
        <%= f.input :email, required: true, error: f.full_error(:email) %>
      </section>

      <section id="shipping_info" class="guest_checkout_info_section">
        <h3>Shipping Details</h3>
        <p>
        <%= f.input :address_line_a, as: :text, required: true, error: f.full_error(:address_line_a) %>
        </p>
        <%= f.input :address_line_b, as: :text %>
        <%= f.input :zip_code, required: true, error: f.full_error(:zip_code) %>
        <div class="phone_number_wrapper guest_info_form_wrapper">
          <label class="phone required"> 
            <abbr title="required">*</abbr>
            Phone
          </label>
          <%= f.select :phone_country_code, country_code_list, required: true %>
          <%= f.input :phone_number, as: :integer, required: true, label: false, wrapper_html: {
            id: 'guest-phone-number',
            class: 'input integer required guest_order_builder_form_phone_number' }
          %>
        </div>
      </section>

      <%= f.simple_fields_for form.item, defaults: {wrapper_html: {class: ''}} do |ff| %>
        <%= ff.input :item_id, as: :hidden %>
        <%= ff.input :size, as: :hidden %>
        <%= ff.input :quantity, as: :hidden %>
      <% end %>

      <section class="guest_checkout_info_section" id="payment_info">
        <h3>Billing Details</h3>
        <div class="flex flex-row space-between">
          <span class="inline-block">Total:</span>
          <span class="inline-block">
            <%= format_price total_amount %>
          </span>
        </div>
        <div class="flex flex-row space-between">
          <span class="inline-block">Shipping: </span>
          <span class="inline-block">0</span>
        </div>
        <div class="flex flex-row space-between checkout-total">
          <span class="inline-block bold">Total </span>
          <span class="inline-block bold">
            <%= format_price(total_amount + shipping) %>
          </span>
        </div>
      </section>

      <section id="pay-me-now">
        <% if outofstock.present? %>
          <div class='place_order_btn_lg btn-outofstock'>Sold Out</div>
        <% elsif show_payment.present? %>
          <%= render partial: "carts/pay", locals: { order_token: order_token } %>
        <% else %>
          <%= f.button :submit, "Place Order", { class: 'place_order_btn_lg' } %>
        <% end %>

        <% if @guest_order_error.present? %>
          <span class="form-inline-error" style="font-size: 0.9em"><%= @guest_order_error %></span>
        <% end %>

      </section>
    <% end %>
  <% end %>
</div>

app/views/carts/_guest_form.html.erb
<div class="checkout">
  <%= turbo_frame_tag 'guest-checkout-form' do %>
    <%= simple_form_for form, url: guest_checkouts_url, method: :post, defaults: {wrapper_html: { class: 'guest_info_form_wrapper'} } do |f| %>
      <section id="user_info" class="guest_checkout_info_section">
        <h3>Contact Info</h3>
        <%= f.input :email, required: true %>
      </section>

      <!-- failing here -->
      <%= f.simple_fields_for form.address_form_builder, defaults: {wrapper_html: {class: ''}} do |ff| %>
        <section id="shipping_info" class="guest_checkout_info_section">
          <h3>Shipping Details</h3>
          <p>
          <%= ff.input :address_line_a, as: :text, required: true, wrapper_html: { class: 'guest_info_form_wrapper' } %>
          </p>
          <%= ff.input :address_line_b, as: :text, wrapper_html: { class: 'guest_info_form_wrapper' } %>
          <%= ff.input :zip_code, required: true, wrapper_html: { class: 'guest_info_form_wrapper' } %>
          <div class="phone_number_wrapper guest_info_form_wrapper">
            <label class="phone required"> 
              <abbr title="required">*</abbr>
              Phone
            </label>
            <%= f.select :phone_country_code, country_code_list, required: true %>
            <%= f.input :phone_number, as: :integer, required: true, label: false, wrapper_html: {
              id: 'guest-phone-number',
              class: 'input integer required guest_order_builder_form_phone_number' }
            %>
          </div>
        </section>
      <% end %>
      <!-- failing here -->

      <%= f.simple_fields_for form.order_item_builder, defaults: {wrapper_html: {class: ''}} do |ff| %>
        <%= ff.input :item_id, as: :hidden, wrapper_html: { class: 'guest_info_form_wrapper' } %>
        <%= ff.input :size, as: :hidden, wrapper_html: { class: 'guest_info_form_wrapper' } %>
        <%= ff.input :quantity, as: :hidden, wrapper_html: { class: 'guest_info_form_wrapper' } %>
      <% end %>

      <section class="guest_checkout_info_section" id="payment_info">
        <h3>Billing Details</h3>

        <div class="flex flex-row space-between">
          <span class="inline-block">Total:</span>
          <span class="inline-block">
            <%= format_price total_amount %>
          </span>
        </div>
        <div class="flex flex-row space-between">
          <span class="inline-block">Shipping: </span>
          <span class="inline-block">0</span>
        </div>
        <div class="flex flex-row space-between checkout-total">
          <span class="inline-block bold">Total </span>
          <span class="inline-block bold">
            <%= format_price(total_amount + shipping) %>
          </span>
        </div>
      </section>

      <section id="pay-me-now">
        <%= render partial: "carts/pay", locals: {
          oos: outofstock, 
          gf: f, 
          show_payment: show_payment, 
          order_token: order_token 

        } %>

        <% if @guest_order_error.present? %>
          <span class="form-inline-error" style="font-size: 0.9em"><%= @guest_order_error %></span>
        <% end %>

      </section>
    <% end %>
  <% end %>
</div>

app/views/carts/_my_order_form.html.erb
  <div class="checkout flex flex-col" style="--gap: 2em" data-controller="address">
    <%= render partial: 'carts/order_error', locals: {
        order_form: order_form,
        errors: errors
    } %>

    <section id="shipping_info" class="guest_checkout_info_section">
      <h3>Shipping Details</h3>

      <%= link_to "Add address", '#', { class: "clean-anchor", data: { action: 'click->address#toggleForm' }} %>
      <%= render partial: 'addresses/form', locals: { form: form } %>

      <% if addresses.length > 0 %>
        <h5> select address </h5>

        <div id="addresses-wrapper">
          <% addresses.each do |address| %>
            <%= render partial: 'addresses/address', locals: { address: address } %>
          <% end %>
        </div>
      <% end %>
    </section>

    <section class="guest_checkout_info_section" id="payment_info">
      <h3>Billing Details</h3>

      <div class="flex flex-row space-between">
        <span class="inline-block">Total:</span>
        <span class="inline-block">
          <%= format_price total_amount %>
        </span>
      </div>

      <div class="flex flex-row space-between">
        <span class="inline-block">Shipping: </span>
        <span class="inline-block">0</span>
      </div>

      <div class="flex flex-row space-between checkout-total">
        <span class="inline-block bold">Total </span>
        <span class="inline-block bold">
          <%= format_price(total_amount) %>
        </span>
      </div>

    </section>

    <section id="pay-me-now">
      <%= render partial: "carts/pay", locals: { 
        my_order: true,
        order_token: order_token, 
        show_payment: show_payment,
        order_form: 
      } %>
    </section>
  </div>

app/views/carts/_order_error.html.erb
<%= turbo_frame_tag 'order-form-error' do %>
  <% errors.each do |error| %>
    <span class="form-inline-error" style="font-size: 0.9em"><%= error %></span>
  <% end %>
<% end %>

app/views/carts/_pay.html.erb
<% show_payment ||= false %>
<% my_order ||= false %>
<% oos ||= false %>

<% if oos.present? %>
  <div class='place_order_btn_lg btn-outofstock'>Sold Out</div>
<% elsif show_payment.present? %>
  <div>
    <%= link_to "Pay", products_url, class: "place_order_btn_lg btn-pay" %>
  </div>
<% elsif my_order.present? %>
  <%= simple_form_for order_form, url: place_my_order_checkouts_url, method: :post do |f| %>
    <%= f.input :address_id, as: :hidden, required: true, input_html: {data: { 'address-target': 'buyAddressID' }} %>
    <%= f.submit "Place Order", class: 'btn place_order_btn_lg' %>
  <% end %>
<% else %>
  <%= gf.button :submit, "Place Order", { class: 'place_order_btn_lg' } %>
<% end %>

app/views/carts/destroy.turbo_stream.erb
<%= turbo_stream.replace 'cart-items-count' do %>
  <%= render partial: 'layouts/cart_items_count', locals: { cart_items_count: @cart_items_count - 1 } %>
<% end %>


<%= turbo_stream.remove "product_item_#{@item_id}" %>

app/views/carts/guest_order.html.erb
<header id="guest-shopping-info-header" class="page-title line-top">
    <h3 class="pi-content-gutter" style="--pi-block-gap: 0">Review order</h3>
</header>

<div class="checkout_wrapper">
    <div class="shopping_info">
        <section id="guest-shopping-list">
            <div class="cart-item">
                <div class="cart-image-wrapper">
                    <%= image_tag @product_item.product.promoted_image %>
                </div>
                <span class="inline-block"><%= @product.title %></span>
                <span class="inline-block"><%= format_price @product.price %></span>
            </div>

            <div class="total-cart-amount">
                <span>Total</span>
                <span>
                    <%= format_price(@total_amount + @shipping) %>
                </span>
            </div>

            <div id="guest-delivery-faq">
                <p>
                It takes 7 days for the item to delivered by our service providers.
                You can return the product to us personally if you don't like it.
                </p>

                <p>
                Please reach out to us, and we will schedule a pickup.
                </p>
            </div>
        </section>
    </div>

    <%= render partial: "carts/guest_form", locals: { 
        form: @form,
        total_amount: @total_amount, 
        shipping: @shipping, 
        outofstock: @outofstock,
        show_payment: @show_payment, 
        order_token: nil
    } %>

</div>

app/views/carts/show.html.erb
<header id="guest-shopping-info-header" class="page-title line-top">
    <h3 class="pi-content-gutter" style="--pi-block-gap: 0">Review order (<%= @cart_items.count %>)</h3>
</header>

<div class="checkout_wrapper">
    <div class="shopping_info">
        <section id="guest-shopping-list">
            <% @cart_items.each do |cart_item| %> 
              <%= render partial: 'carts/cart_item', locals: { product_item: cart_item.product_item, product: cart_item.product_item.product } %>
            <% end %>

            <div class="total-cart-amount">
                <span>Total</span>
                <span>
                    <%= format_price(@pricing.order_full) %>
                </span>
            </div>

            <div id="guest-delivery-faq">
                <p>
                It takes 7 days for the item to delivered by our service providers.
                You can return the product to us personally if you don't like it.
                </p>

                <p>
                Please reach out to us, and we will schedule a pickup.
                </p>
            </div>
        </section>
    </div>

    <%= render partial: "carts/my_order_form", locals: { 
        form: @form, 
        order_form: @order_form,
        addresses: @addresses,
        total_amount: @pricing.order_full,
        shipping: @pricing.shipping,
        show_payment: @show_payment,
        cart_items: @cart_items,
        errors: @order_errors || [],
        order_token: nil } %>

</div>

app/views/carts/update.turbo_stream.erb
<%= turbo_stream.replace 'cart-items-count' do %>
  <%= render partial: 'layouts/cart_items_count', locals: { cart_items_count: @cart_items_count + 1 } %>
<% end %>

<%= turbo_stream.replace 'cart-success' do %>
  <%= render partial: 'products/cart_messages', locals: { errors: [], success: @cart_success_msgs } %>
<% end %>