config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  # root "articles#index"

  root to: 'home#index'

  get '/accounts', to: 'accounts#show'
  post '/accounts/login', to: 'accounts#login'
  post '/accounts/signup', to: 'accounts#signup'
  delete '/accounts/logout', to: 'accounts#logout'

  patch '/accounts/recover', to: 'accounts#trigger_recover_password'
  get '/accounts/recover', to: 'accounts#validate_recovery_token'
  patch '/accounts/reset/password', to: 'accounts#reset_password'

  resources :categories, only: %i[index]
  resources :products, only: %i[show index]

  resources :carts, except: %i[new delete] do
  end

  delete '/carts/remove/:id', to: 'carts#remove', as: 'remove_from_cart'

  resources :carts do
    collection do
      get '/guest/:token', to: 'carts#guest_order', as: 'guest_order'
      get '/my/review', to: 'carts#show'
    end
  end

  resources :checkouts do
    collection do
      post '/guest/buy', to: 'checkouts#guest_buy'
      post '/guest', to: 'checkouts#guest_create'

      post '/direct_buy', to: 'checkouts#direct_buy'
      post '/me/buy', to: 'checkouts#create', as: 'place_my_order'
    end
  end

  get '/me/addresses', to: 'addresses#index', as: 'addresses'
  get '/me/addresses/:id', to: 'address#edit', as: 'edit_address'

  # this is an idempotent route, if its update the params[:id] is present?
  # else its a new address for the current_user
  patch '/me/addresses', to: 'addresses#update', as: 'add_address'
  delete '/me/addresses/:id', to: 'addresses#delete', as: 'delete_address'

  match '*unmatched', to: 'application#not_found_method', via: :all
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :logged_in?

  def index
    @form = AddressFormBuilder.new
    @addresses = Address.vieweable(current_user.id)
  end

  def update
    @form = AddressFormBuilder.new(*address_params)
    unless @form.valid?
      return respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace(
            'address-form',
            partial: 'addresses/form',
            locals: {
              form: @form,
              form_state: 'show'
            }
          )
        end

        format.html { redirect_back fallback_location: my_review_carts_url, status: 422 }
      end
    end

    address_model_params = {
      address_line_a: @form.address_line_a,
      address_line_b: @form.address_line_b,
      zip_code: @form.zip_code,
      alternate_number: @form.alternate_number,
      tag: @form.tag.capitalize
    }

    @address = if new_address?
                 current_user.addresses.create(address_model_params)
               else
                 current_address.update(address_model_params)
               end

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_back fallback_location: my_review_carts_url, status: 200 }
    end
  end

  def delete
    current_address.update(deleted_at: Time.now.utc)

    respond_to do |f|
      f.turbo_stream { render turbo_stream: turbo_stream.remove("#{helpers.dom_id(current_address)}_details") }
    end
  end

  private

  def new_address?
    !params[:id].present?
  end

  def current_address
    @current_address ||= Address.find_by(id: params[:id], user_id: current_user.id)
  end

  def address_params
    params.require(:address_form_builder).permit(*AddressFormBuilder.attributes)
  end
end

app/views/addresses/_address.html.erb
<section id='<%= "#{dom_id(address)}_details"%>' data-addr="<%= address.id %>" data-address-target="addressItem" data-action='click->address#selectAddress' class="address-container flex flex-col">
  <h4><%= address.tag %></h4>
  <div class="address-details-line-a flex flex-row">
    <%= address.address_line_a %>
  </div>
  <div class="address-details-zip code flex flex-row">
    <span class="zip-code-label">Zip Code</span>
    <%= address.zip_code %>
    </span>
  </div>
  <!--
    <span class="address-details-phone">
    <%= simple_mask(address.alternate_number, 5) %>
    </span>
  -->

  <div class="address-actions flex flex-row space-between" id='<%= dom_id(address) %>'>
    <!-- <%= link_to "Edit", edit_address_path(address) %> -->
    <%= button_to "Delete", delete_address_path(address), method: :delete, data: { confirm: 'Are you sure?', disable_with: 'loading...' } %>
  </div>
</section>

app/views/addresses/_form.html.erb
<% form_state ||= 'hide' %>
<%= simple_form_for form, url: add_address_url, method: :patch, html: { class: "guest_checkout_info_section #{form_state}", id: 'address-form', 'aria-expanded': false, data: { 'address-target': 'addAddressForm'} } do |f| %>
  <%= f.input :tag, required: false, placeholder: '[Optional] Home/Other', wrapper_html: { class: 'guest_info_form_wrapper' } %>
  <%= f.input :address_line_a, as: :text, required: true, wrapper_html: { class: 'guest_info_form_wrapper' } %>
  <%= f.input :address_line_b, as: :text, wrapper_html: { class: 'guest_info_form_wrapper' } %>
  <%= f.input :zip_code, required: true, wrapper_html: { class: 'guest_info_form_wrapper' } %>
  <div class="phone_number_wrapper guest_info_form_wrapper">
    <label class="phone required"> 
      <!--<abbr title="required">*</abbr>-->
      Phone
    </label>
    <%= f.select :country_code, country_code_list, required: true %>
    <%= f.input :alternate_phone_number, as: :integer, required: true, label: false, wrapper_html: {
      id: 'guest-phone-number',
      class: 'input integer required guest_order_builder_form_phone_number' }
    %>
  </div>

  <%= f.button :submit, "Save", { class: 'btn' } %>
<% end %>

app/views/addresses/update.turbo_stream.erb
<%= turbo_stream.replace 'address-form' do %>
  <%= render partial: 'addresses/form', locals: { form: AddressFormBuilder.new } %>
<% end %>

<% if @address.present? %>
  <%= turbo_stream.prepend 'addresses-wrapper' do %>
    <%= render partial: 'addresses/address', locals: { address: @address } %>
  <% end %>
<% end %>