config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  # root "articles#index"

  root to: 'home#index'

  get '/accounts', to: 'accounts#show'
  post '/accounts/login', to: 'accounts#login'
  post '/accounts/signup', to: 'accounts#signup'
  delete '/accounts/logout', to: 'accounts#logout'

  patch '/accounts/recover', to: 'accounts#trigger_recover_password'
  get '/accounts/recover', to: 'accounts#validate_recovery_token'
  patch '/accounts/reset/password', to: 'accounts#reset_password'

  resources :categories, only: %i[index]
  resources :products, only: %i[show index]

  resources :carts, except: %i[new delete] do
  end

  delete '/carts/remove/:id', to: 'carts#remove', as: 'remove_from_cart'

  resources :carts do
    collection do
      get '/guest/:token', to: 'carts#guest_order', as: 'guest_order'
      get '/my/review', to: 'carts#show'
    end
  end

  resources :checkouts do
    collection do
      post '/guest/buy', to: 'checkouts#guest_buy'
      post '/guest', to: 'checkouts#guest_create'

      post '/direct_buy', to: 'checkouts#direct_buy'
      post '/me/buy', to: 'checkouts#create', as: 'place_my_order'
    end
  end

  get '/me/addresses', to: 'addresses#index', as: 'addresses'
  get '/me/addresses/:id', to: 'address#edit', as: 'edit_address'

  # this is an idempotent route, if its update the params[:id] is present?
  # else its a new address for the current_user
  patch '/me/addresses', to: 'addresses#update', as: 'add_address'
  delete '/me/addresses/:id', to: 'addresses#delete', as: 'delete_address'

  match '*unmatched', to: 'application#not_found_method', via: :all
end

app/models/product.rb
class Product < ApplicationRecord # :nodoc:
  include Uidable

  GARMENT_TYPES = {
    ::GarmentTypes::OVER_TEE => 'Oversized Tees'.freeze,
    ::GarmentTypes::REGULAR_TEE => 'Regular Tees'.freeze,
    ::GarmentTypes::PANTIES => 'Baggy Tracks'.freeze
  }

  has_one :product_item
  belongs_to :category

  before_validation :set_sku_provider, :set_gender

  validates :sku, presence: true, length: { in: 5..100 }
  validates :sku_provider, presence: true
  validates :title, presence: true
  validates :gender, presence: true, inclusion: %w[unisex male female]
  # validates :description

  # in paisa or cents or lowest denomination
  validates :price, numericality: { only_integer: true }
  validates :images, presence: true
  validates :available, inclusion: [true, false]
  validates :is_limited_edition, inclusion: [true, false]

  validates :category_id, presence: true

  # created_at, #updated_at

  def images
    ImageWrapper.from_json(self[:images])
  end

  def promoted_image
    return 'https://placehold.co/400x400' unless images.present?

    images.high(images.images[0])
  end

  def thumbs
    images.images.map do |img|
      images.thumb(img)
    end
  end

  def product_images
    images.split(',')
  end

  def oversized_tee?
    product_type == ::GarmentTypes::OVER_TEE
  end

  def regular_tee?
    product_type == ::GarmentTypes::REGULAR_TEE
  end

  def pants?
    product_type == ::GarmentTypes::PANTIES
  end

  def self.available
    where({ available: true }).order('created_at ASC')
  end

  def self.featured
    available.order('updated_at DESC').limit(6)
  end

  private

  def set_sku_provider
    self.sku_provider = 'default' unless sku_provider.present?
  end

  def set_gender
    self.gender = 'unisex' unless gender.present?
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :add_products_crumb, only: %i[show index]
  before_action :set_cart_error_and_success_vars, only: :show

  def index
    @categories = Category.all
    @products = Product.available.joins(:product_item)
      .where(category_id: @categories.pluck(:id))
  end

  def show
    details = ProductDetail.new(params[:id])

    @product_details = details.get or not_found
    @product = details.product

    @guest_form = GuestBuyForm.new(quantity: 1)
    @user_form = GuestBuyForm.new(quantity: 1) if logged_in?

    add_breadcrumb(@product.title, nil)
  end

  private

  def add_products_crumb
    add_breadcrumb('Products', products_url)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  include ApplicationHelper

  def size_options_for_select(size_chart = [])
    size_chart.map do |chart|
      [size_to_text(chart), chart[:size]]
    end
  end

  def size_to_text(chart)
    chart[:size].to_s
  end

  # checks if the product item is already added to cart
  # we assume that current_user will be there, we need to validate on cart_token
  def can_add_to_cart?(item_id)
    return false unless current_user.present? && current_user.member?
    return true unless current_cart.present?

    !current_cart.find { |cart| cart.product_item_id == item_id }.present?
  end

  # TODO: see if we need to add @cart_error_messages here
  def buttton_class_for_add_to_cart(item_id)
    return 'enabled' if can_add_to_cart?(item_id)

    'disabled'
  end
end

app/views/products/_cart_messages.html.erb
<section id="cart-errors" class="flex flex-col cart-messages">
  <% errors.each do |msg| %>
    <span class="cart-error-msg"><%= msg %></span>
  <% end %>
</section>
<section id="cart-success" class="flex flex-col cart-messages">
  <% success.each do |msg| %>
    <span class="cart-success-msg"><%= msg %></span>
  <% end %>
</section>
  

app/views/products/_form.html.erb
<% default_button_class =   %>

<%= simple_form_for form, url: url, method: method, html: html_opts do |f| %>
  <%= f.input :item_id,
    as: :hidden,
    input_html: {
      data: {'cart-add-target': 'buyNowItemID' },
      value: product_details[:item_id] }
    %>
  <%= f.input :size,
    as: :hidden,
    input_html: {
      data: {'cart-add-target': 'buyNowSize'} }
    %>
  <%= f.input :quantity,
    as: :hidden,
    input_html: {
      data: {'cart-add-target': 'buyNowQuantity'},
      value: 1 }
    %>
  <%= f.button :submit,
    "#{submit_button_text}",
    button_opts
  %>
<% end %>

app/views/products/_product.html.erb
<li id="<%= dom_id product %>">
  <img src='<%= image_path(product.images.thumb(product.images.images[0])) %>'/>
  <span><%= product.title %></span>

  <a class="card-overlay" href="<%= product_path(product) %>"></a>
</li>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<div class="screen-gap"></div>

<div class="explore-all-wrapper">
  <div id="categories">
    <div class="category_item active" id="default-category">
      <%= link_to "all", "#" %>
    </div>
    <% @categories.each do |category| %>
      <%= render category %>
    <% end %>
  </div>

  <section class="product-listing container-max-width">
    <div class="items-wrapper">
      <ul class="product-items-listing">
        <% @products.each do |product| %>
          <%= render product  %>
        <% end  %>
      </ul>
    </div>
  </section>

</div>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<header class="page-title product-title line-top">
    <h2><%= @product.title %></h2>
</header>
<div
        id="product_details_wrapper"
        data-controller="cart-add"
        data-cart-add-target="productItem"
        data-cart-url="<%= carts_url %>"
        data-is-logged-in="<%= logged_in? ? 'true' : 'false' %>"
        data-item-id="<%= @product_details[:item_id] %>"
        >

        <div class="flex flex-col full-width">
            <div class="product_details__image_wrapper">
                <!-- need to show all image in c arousal -->
                <%= image_tag @product.promoted_image %>
            </div>

        </div>

        <div class="flex flex-col full-width">
            <div class="product_details__info">
                <section id="description">
                    <% if @product.description.present? %>
                        <em><%= @product.description %></em>
                    <% else %>
                        <em>
                            Get your X factor out. Professor mixed up in the lab, so did we.
                        </em>
                    <% end %>
                </section>
                <section class="size-select">
                    <header class="flex flex-row align-end" style="--gap: 2em;">
                        <h3 class="product-option-header">select size</h3>
                        <a class="product-option-helper" href="#">size guide</a>
                    </header>
                    <ul class="sizes">
                        <% size_options_for_select(@product_details.size_chart).each do |size| %>
                            <li>
                                <%= radio_button_tag :size_id, 
                                    size[1],
                                    false, 
                                    {
                                        class: 'product-size-option',
                                        data: {
                                            cart_add_target: 'selectSize',
                                            error_msg: 'please select a size',
                                            action: 'click->cart-add#setSize'}
                                    }
                                %>
                            <%= label_tag "size_id_#{size[1]}", size[0] %>
                            </li>
                        <% end %>
                    </ul>
                    <div data-cart-add-target="formActionSizeError" class="form-inline-error select-size">
                    </div>
                </section>
            </div>

            <section id="chaufferr" class="<%= logged_in? ? 'logged-in': '' %>">
                <p class="price"><%= format_price @product.price %></p>

                <div class="cta_component">
                    <% buy_url = logged_in? ? direct_buy_checkouts_url : guest_buy_checkouts_url %>
                    <%= render partial: "products/form", locals: {
                        form: @guest_form,
                        url: buy_url,
                        method: :post,
                        product_details: @product_details,
                        submit_button_text: 'Buy Now',
                        html_opts: { data: { action: 'submit->cart-add#directBuy'} },
                        button_opts: { class: 'product_details__cta_btn', data: {'cart-add-target': 'buyNowBtn'} }
                    } %>

                    <% if logged_in? %>
                        <% btn_class = ["product_details__cta_btn add-to-cart-btn", buttton_class_for_add_to_cart(@product_details[:item_id])].join(' ') %>
                        <%= render partial: "products/form", locals: {
                            form: @user_form,
                            url: new_cart_url,
                            method: :patch,
                            product_details: @product_details,
                            submit_button_text: 'Add to Cart',
                            html_opts: { data: { action: 'submit->cart-add#validate', state: buttton_class_for_add_to_cart(@product_details[:item_id]) } },
                            button_opts: { class: btn_class, id: 'add-to-cart', data: { 'cart-add-target': 'addToCart' } }
                        } %>
                    <% end %>
                </div>
            </section>

            <%= render partial: "products/cart_messages", locals: { errors: @cart_error_msgs, success: @cart_success_msgs } %>
            
        </div>
</div>