config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  # root "articles#index"

  root to: 'home#index'

  get '/accounts', to: 'accounts#show'
  post '/accounts/login', to: 'accounts#login'
  post '/accounts/signup', to: 'accounts#signup'
  delete '/accounts/logout', to: 'accounts#logout'

  patch '/accounts/recover', to: 'accounts#trigger_recover_password'
  get '/accounts/recover', to: 'accounts#validate_recovery_token'
  patch '/accounts/reset/password', to: 'accounts#reset_password'

  resources :categories, only: %i[index]
  resources :products, only: %i[show index]

  resources :carts, except: %i[new delete] do
  end

  delete '/carts/remove/:id', to: 'carts#remove', as: 'remove_from_cart'

  resources :carts do
    collection do
      get '/guest/:token', to: 'carts#guest_order', as: 'guest_order'
      get '/my/review', to: 'carts#show'
    end
  end

  resources :checkouts do
    collection do
      post '/guest/buy', to: 'checkouts#guest_buy'
      post '/guest', to: 'checkouts#guest_create'

      post '/direct_buy', to: 'checkouts#direct_buy'
      post '/me/buy', to: 'checkouts#create', as: 'place_my_order'
    end
  end

  get '/me/addresses', to: 'addresses#index', as: 'addresses'
  get '/me/addresses/:id', to: 'address#edit', as: 'edit_address'

  # this is an idempotent route, if its update the params[:id] is present?
  # else its a new address for the current_user
  patch '/me/addresses', to: 'addresses#update', as: 'add_address'
  delete '/me/addresses/:id', to: 'addresses#delete', as: 'delete_address'

  match '*unmatched', to: 'application#not_found_method', via: :all
end

app/views/layouts/_breadcrumb.html.erb
<% if breadcrumbs.length > 0 %>
    <div class="breadcrumbs">
        <% unless controller_name == "home" && action_name == "index" %>
            <%= link_to "Home", root_path, class: 'breadcrumb' %>
        <% end %>
        <% breadcrumbs.each do |item| %>
            <% if item[:skip] %>
                <% next %>
            <% elsif item == breadcrumbs.last %>
                <a href="#" class="clean-anchor breadcrumb">
                    <%= item[:title] %>
                </a>
            <% else %>
                <%= link_to item[:title], item[:url], class: 'breadcrumb' %>
            <% end %>
        <% end %>
    </div>
<% end %>

app/views/layouts/_cart_items_count.html.erb
<div id="cart-items-count">
  <span>
    <% if cart_items_count > 0 %>
      <span class="cart-items-count-text"><%= cart_items_count %></span>
    <% end %>
  </span>
  <% cart_review_url = cart_items_count.zero? ? "#" : my_review_carts_url %>
  <%= link_to 'Cart', cart_review_url,  { class: 'header-nav' }  %>
</div>

app/views/layouts/_flash.html.erb
<div class="toast">
    <section class='<%= "toaster_contents toast-#{flash_type.downcase}" %>'>

    <div class="toast-body">
        <span><%= flash_msg %></span>
        <span class="close" data-action="click->toast#closeToast" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </span>
    </div>
    </section>
</div>

app/views/layouts/_header.html.erb
<header class="nav-header" data-controller="header-nav">
  <div id="app-logo">
    <%= link_to 'mr.notorious', root_path, { class: "clean-anchor" } %>
  </div>

  <button class="nav-toggle" aria-controls="primary-nav" data-header-nav-target="menuToggler" data-action="header-nav#toggleSlideMenuCtrl" aria-expanded="false">
    <span class="material-symbols-outlined nav-toggle-icon show" id="menu" data-header-nav-target="hamOpen">menu</span>
    <span class="material-symbols-outlined nav-toggle-icon" id="close" data-header-nav-target="hamClose">close</span>
    <span class="sr-only">Menu</span>
  </button>

  <nav class="nav-options">
    <ul id="primary-nav" data-state="close" data-header-nav-target="slideMenu">
      <% if logged_in? %>
        <li>
        <span aria-hidden="true" class="material-symbols-outlined">
          shopping_cart
        </span>

        <%= render partial: 'layouts/cart_items_count', locals: {cart_items_count:} %>
        
        </li>
        <li>
          <span aria-hidden="true" class="material-symbols-outlined">
            account_circle
          </span>
          <%= link_to "Profile", accounts_url, class: 'clean-anchor header-nav' %>
        </li>
        <li>
          <span aria-hidden="true" class="material-symbols-outlined">
            account_circle
          </span>
          <%= link_to "Logout", accounts_logout_url, data: { "turbo-method": :delete }, class: 'clean-anchor header-nav' %>
        </li>
      <% else %>
        <li>
          <span aria-hidden="true" class="material-symbols-outlined">
            account_circle
          </span>
          <%= link_to "Accounts", accounts_url, class: 'clean-anchor header-nav' %>
        </li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>mr. notorious</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body id="app">
    <%= render partial: "layouts/header", locals: {cart_items_count: cart_items_count} %>
    <%= render partial: "layouts/breadcrumb" %>

      <div class="toast-wrapper" id="turbo-toast" data-toast-target="toaster" data-controller="toast">
        <% flash.each do |type, msgs| %>
          <% if msgs.is_a?(String) %>
            <%= render partial: 'layouts/flash', locals: { flash_type: type, flash_msg: msgs } %>
          <% elsif msgs.is_a?(Array) %>
            <% msgs.each do |msg| %>
              <%= render partial: 'layouts/flash', locals: { flash_type: type, flash_msg: msg } %>
            <% end %>
          <% end %>
        <% end %>
      </div>
      <%= yield %>
  </body>

  <%= javascript_importmap_tags %>
</html>